export const FETCH_DATA_TVSHOW = "FETCH_DATA_TVSHOW";
export const CHANGE_TVSHOW_POSITION = "CHANGE_TVSHOW_POSITION";
export const TVSHOW_DETAILS = "TVSHOW_DETAILS";
export const TVSHOW_DETAILS_SHOW = "TVSHOW_DETAILS_SHOW";
